name: Auto-Update Portal Mirror
on:
  schedule:
    - cron: "0 6 * * *"  # Daily at 6 AM
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download and Update Portal
        run: |
          # Follow redirects to get the actual file
          curl -L -o portal.min.js "https://unpkg.com/@tryghost/portal@latest/umd/portal.min.js"
          
          # Apply your customizations
          sed -i 's/jamie/YourName/g' portal.min.js
          
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add portal.min.js
          git diff --staged --quiet || git commit -m "Auto-update Portal $(date)"
          git push
